apiVersion: v1
kind: Service
metadata:
  name: autoscaling-microservice
  namespace: autoscaling-demo
spec:
  type: ClusterIP
  selector:
    app: autoscaling-microservice
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
